name: mf_auth
description: Módulo de autenticación para la aplicación Boilerplate
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Dependencias compartidas
  shared_dependencies:
    path: ../shared_dependencies
    
  # Dependencias específicas
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5
  get_it: ^7.2.0
  shared_preferences: ^2.1.0
  validators: ^3.0.0
  another_flushbar: ^1.12.29
  json_annotation: ^4.8.1
  go_router: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  mobx_codegen: ^2.2.0
  json_serializable: ^6.7.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # Nota: En módulos de microfrontend, las fuentes se definen en el proyecto shell (principal)
  # y no necesitan ser redefinidas aquí, ya que son compartidas por toda la aplicación.
  # Sin embargo, si ejecutas este módulo de forma independiente para pruebas,
  # podrías definir las fuentes aquí temporalmente.
  
  # Ejemplo de definición de fuentes (solo para pruebas independientes):
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: ../assets/fonts/Poppins-Light.ttf
  #         weight: 300
  #       - asset: ../assets/fonts/Poppins-Regular.ttf
  #         weight: 400
  #       - asset: ../assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: ../assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: ../assets/fonts/Poppins-Bold.ttf
  #         weight: 700
